In [60]:
from sklearn.model_selection import train_test_split,cross_val_score
from keras.models import Sequential
from keras.layers import Dense
import matplotlib.pyplot as plt

In [61]:
import pandas as pd
data=pd.read_csv("Sayantan Combine Data Set.csv")
data.head(5)
data.dropna(inplace=True)
from sklearn.preprocessing import LabelEncoder,StandardScaler,OneHotEncoder
from sklearn.metrics import accuracy_score,f1_score,precision_score,confusion_matrix

scaler=StandardScaler()
encoder=OneHotEncoder(sparse_output=False)

In [62]:
data.head(5)

PZ -REF  FP1-REF  FP2-REF  F7 -REF  F3 -REF  FZ -REF  F4 -REF  F8 -REF  \
1      4.0       -5      -80       -5      -22      -36     -131      -55   
2     -6.0      -10      -84        1      -20      -40     -145      -55   
3    -13.0       -9      -84        7      -14      -40     -154      -55   
4    -18.0       -4      -82       11       -8      -36     -162      -57   
5    -22.0        5      -81        7       -4      -33     -169      -61   

   T3 -REF  C3 -REF  ...  C4 -REF  T4 -REF  T5 -REF  P3 -REF  P4 -REF  \
1      -14       10  ...      -18       -1       24      -13      -12   
2      -11       16  ...      -23      -12       26      -10      -14   
3       -7       22  ...      -27      -21       28      -10      -15   
4       -4       26  ...      -32      -29       29      -12      -15   
5       -3       27  ...      -40      -37       26      -16      -15   

   T6 -REF  O1 -REF  OZ -REF  O2 -REF  Class  
1        7       29      -15      -10   Urge  
2        9       29       -8       -7   Urge  
3       10       27        5       -5   Urge  
4        7       24       20       -6   Urge  
5        2       18       33       -8   Urge  

[5 rows x 21 columns]

In [63]:
data['Class'].value_counts()

Class
Rage            2560
Satisfaction    2560
Urge            2558
Name: count, dtype: int64

In [64]:
x=data.iloc[:,:20].values

In [65]:
y=data.iloc[:,20:].values.reshape(-1,1)

In [66]:
y

array([['Urge'],
       ['Urge'],
       ['Urge'],
       ...,
       ['Satisfaction'],
       ['Satisfaction'],
       ['Satisfaction']], dtype=object)

In [67]:
y=encoder.fit_transform(y)

In [68]:
y

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.]])

Urge : 3,
Rage: 1,
Satisfaction: 2

In [69]:
results_dict={
    0:"Rage",
    1:"Satisfaction",
    2:"Urge"
}

In [70]:
x

array([[   4.,   -5.,  -80., ...,   29.,  -15.,  -10.],
       [  -6.,  -10.,  -84., ...,   29.,   -8.,   -7.],
       [ -13.,   -9.,  -84., ...,   27.,    5.,   -5.],
       ...,
       [-108., -110.,   20., ...,  -62., -117., -170.],
       [-109., -108.,   17., ...,  -60., -131., -172.],
       [-107., -107.,   12., ...,  -58., -133., -174.]])

In [71]:
x=scaler.fit_transform(x)

In [72]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=2)

In [73]:
y_train

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       ...,
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [74]:
ann=Sequential()
ann.add(Dense(units=10,activation='relu',input_shape=(20,)))
ann.add(Dense(units=10,activation='relu'))
ann.add(Dense(units=3,activation='softmax'))

ann.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
ann.fit(x_train,y_train,epochs=100,batch_size=100)

Epoch 1/100


54/54 [==============================] - 1s 2ms/step - loss: 1.0342 - accuracy: 0.3642
Epoch 2/100
54/54 [==============================] - 0s 2ms/step - loss: 0.9345 - accuracy: 0.5125
Epoch 3/100
54/54 [==============================] - 0s 2ms/step - loss: 0.8540 - accuracy: 0.6139
Epoch 4/100
54/54 [==============================] - 0s 2ms/step - loss: 0.7642 - accuracy: 0.6643
Epoch 5/100
54/54 [==============================] - 0s 2ms/step - loss: 0.6627 - accuracy: 0.6984
Epoch 6/100
54/54 [==============================] - 0s 2ms/step - loss: 0.5602 - accuracy: 0.7849
Epoch 7/100
54/54 [==============================] - 0s 2ms/step - loss: 0.4600 - accuracy: 0.8712
Epoch 8/100
54/54 [==============================] - 0s 2ms/step - loss: 0.3713 - accuracy: 0.9122
Epoch 9/100
54/54 [==============================] - 0s 2ms/step - loss: 0.3023 - accuracy: 0.9304
Epoch 10/100
54/54 [==============================] - 0s 2ms/step - loss: 0.2535 - accuracy: 0.9403
Epoch 11/100
54/54 [=

In [75]:
loss, accuracy = ann.evaluate(x_test, y_test)

72/72 [==============================] - 1s 2ms/step - loss: 0.0010 - accuracy: 1.0000


In [76]:
1-loss

0.9989943151595071

In [77]:
accuracy

1.0

In [78]:
prediction=ann.predict(x_test)

 1/72 [..............................] - ETA: 5s

72/72 [==============================] - 0s 2ms/step


In [79]:
ann.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 10)                210       
                                                                 
 dense_4 (Dense)             (None, 10)                110       
                                                                 
 dense_5 (Dense)             (None, 3)                 33        
                                                                 
Total params: 353 (1.38 KB)
Trainable params: 353 (1.38 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [80]:
prediction

array([[1.0000000e+00, 2.5881222e-14, 8.8385936e-18],
       [3.6398720e-10, 1.0000000e+00, 3.8667290e-13],
       [9.5148749e-08, 8.1807922e-10, 9.9999988e-01],
       ...,
       [1.0000000e+00, 1.9298864e-18, 2.5830663e-10],
       [6.1333533e-10, 9.9999964e-01, 3.4933885e-07],
       [1.0000000e+00, 3.5653771e-16, 2.7167994e-20]], dtype=float32)

In [81]:
type(prediction)

numpy.ndarray

In [82]:
!pip install numpy


[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [83]:
import numpy as np
results_labels=[]
results=[]
for rows in prediction:
   arg=rows.argmax()
   results.append(arg)
   if arg in results_dict.keys():
        results_labels.append(results_dict[arg])

In [84]:
results

[0,
 1,
 2,
 1,
 2,
 2,
 2,
 1,
 2,
 0,
 1,
 2,
 1,
 2,
 0,
 1,
 0,
 1,
 2,
 0,
 1,
 2,
 1,
 0,
 2,
 2,
 1,
 0,
 1,
 2,
 1,
 0,
 2,
 1,
 0,
 0,
 2,
 0,
 2,
 0,
 0,
 2,
 0,
 1,
 1,
 0,
 0,
 2,
 0,
 2,
 1,
 0,
 1,
 2,
 0,
 1,
 2,
 2,
 2,
 0,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 2,
 2,
 0,
 0,
 1,
 1,
 2,
 0,
 1,
 1,
 0,
 0,
 0,
 2,
 2,
 0,
 2,
 2,
 2,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 1,
 2,
 1,
 2,
 1,
 2,
 1,
 0,
 0,
 1,
 2,
 0,
 2,
 1,
 1,
 1,
 1,
 0,
 2,
 2,
 1,
 0,
 1,
 2,
 2,
 1,
 0,
 1,
 0,
 1,
 0,
 2,
 2,
 0,
 2,
 2,
 2,
 0,
 0,
 0,
 1,
 2,
 1,
 1,
 2,
 1,
 2,
 0,
 2,
 1,
 1,
 1,
 0,
 0,
 2,
 1,
 0,
 0,
 2,
 2,
 0,
 0,
 0,
 2,
 0,
 2,
 2,
 2,
 2,
 1,
 0,
 0,
 0,
 1,
 1,
 2,
 2,
 2,
 0,
 2,
 1,
 2,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 2,
 1,
 1,
 2,
 2,
 1,
 2,
 2,
 1,
 1,
 0,
 2,
 2,
 1,
 2,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 2,
 0,
 2,
 0,
 0,
 1,
 1,
 2,
 0,
 2,
 1,
 0,
 0,
 2,
 0,
 0,
 2,
 1,
 0,
 2,
 1,
 0,
 1,
 0,
 0,
 2,
 2,
 0,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 0,
 2,


In [85]:
results_labels

['Rage',
 'Satisfaction',
 'Urge',
 'Satisfaction',
 'Urge',
 'Urge',
 'Urge',
 'Satisfaction',
 'Urge',
 'Rage',
 'Satisfaction',
 'Urge',
 'Satisfaction',
 'Urge',
 'Rage',
 'Satisfaction',
 'Rage',
 'Satisfaction',
 'Urge',
 'Rage',
 'Satisfaction',
 'Urge',
 'Satisfaction',
 'Rage',
 'Urge',
 'Urge',
 'Satisfaction',
 'Rage',
 'Satisfaction',
 'Urge',
 'Satisfaction',
 'Rage',
 'Urge',
 'Satisfaction',
 'Rage',
 'Rage',
 'Urge',
 'Rage',
 'Urge',
 'Rage',
 'Rage',
 'Urge',
 'Rage',
 'Satisfaction',
 'Satisfaction',
 'Rage',
 'Rage',
 'Urge',
 'Rage',
 'Urge',
 'Satisfaction',
 'Rage',
 'Satisfaction',
 'Urge',
 'Rage',
 'Satisfaction',
 'Urge',
 'Urge',
 'Urge',
 'Rage',
 'Urge',
 'Satisfaction',
 'Satisfaction',
 'Satisfaction',
 'Satisfaction',
 'Satisfaction',
 'Satisfaction',
 'Satisfaction',
 'Rage',
 'Rage',
 'Urge',
 'Urge',
 'Rage',
 'Rage',
 'Satisfaction',
 'Satisfaction',
 'Urge',
 'Rage',
 'Satisfaction',
 'Satisfaction',
 'Rage',
 'Rage',
 'Rage',
 'Urge',
 'Urge',
 'R

In [86]:
results=np.array(results).reshape(-1,1)

In [87]:
results

array([[0],
       [1],
       [2],
       ...,
       [0],
       [1],
       [0]], dtype=int64)

In [88]:
expected_results=[]

for row in y_test:
    expected_results.append(row.argmax())

In [89]:
expected_results=np.array(expected_results).reshape(-1,1)

In [90]:
expected_results

array([[0],
       [1],
       [2],
       ...,
       [0],
       [1],
       [0]], dtype=int64)

In [91]:
accuracy_score(expected_results,results)

1.0

In [92]:
precision_score(expected_results,results,average=None)

array([1., 1., 1.])

In [93]:
f1_score(expected_results,results,average=None)

array([1., 1., 1.])

In [94]:
confusion_matrix(expected_results,results)

array([[750,   0,   0],
       [  0, 758,   0],
       [  0,   0, 796]], dtype=int64)