In [2]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler,LabelEncoder,MinMaxScaler
np.set_printoptions(threshold=np.inf)
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
scaler=MinMaxScaler()

In [3]:
happy=pd.read_csv("./eeg data emotion/happy.csv")
sad=pd.read_csv("./eeg data emotion/sad.csv")

In [4]:
happy['Y']=0
sad['Y']=1

In [5]:
happy=happy.sample(100)
sad=sad.sample(100)

In [6]:
X1=happy.iloc[:,:19].values
X2=sad.iloc[:,:19].values

X1=scaler.fit_transform(X1)
X2=scaler.fit_transform(X2)

In [7]:
X1

array([[0.28834951, 0.29066107, 0.30334728, 0.31058358, 0.40434783,
        0.74358974, 0.34867777, 0.33146067, 0.33483146, 0.3194292 ,
        0.29040404, 0.35926305, 0.27318046, 0.34042553, 0.31204188,
        0.28987069, 0.25646329, 0.29927667, 0.26295947],
       [0.25436893, 0.20566632, 0.18514644, 0.20672601, 0.19130435,
        0.31196581, 0.25171401, 0.1752809 , 0.18539326, 0.17343578,
        0.20454545, 0.21494371, 0.34895314, 0.19148936, 0.13507853,
        0.18426724, 0.16959669, 0.17902351, 0.21677663],
       [0.32621359, 0.38300105, 0.35774059, 0.38872404, 0.54347826,
        0.55982906, 0.34182174, 0.34382022, 0.34044944, 0.34357849,
        0.39393939, 0.34288639, 0.4227318 , 0.39941973, 0.35287958,
        0.39655172, 0.37642192, 0.37884268, 0.37700283],
       [0.25825243, 0.33788038, 0.32635983, 0.35806133, 0.33478261,
        0.53418803, 0.30852106, 0.34157303, 0.30337079, 0.32381998,
        0.22979798, 0.31218014, 0.34695912, 0.28916828, 0.27643979,
        0.307

In [8]:
X2

array([[0.51375195, 0.53841776, 0.49284928, 0.53085745, 0.55871886,
        0.50653266, 0.62128326, 0.55232558, 0.57840909, 0.55130338,
        0.63613232, 0.56091954, 0.55696935, 0.50628072, 0.50928382,
        0.49764767, 0.52291105, 0.54041451, 0.5452183 ],
       [0.513233  , 0.54524758, 0.54070407, 0.52157291, 0.54181495,
        0.48844221, 0.60824204, 0.54476744, 0.59545455, 0.58957293,
        0.64478372, 0.52356322, 0.55754772, 0.51064992, 0.50981432,
        0.52587559, 0.5541779 , 0.49740933, 0.5524948 ],
       [0.56408926, 0.56687536, 0.54675468, 0.56089569, 0.54626335,
        0.50050251, 0.637976  , 0.57151163, 0.59772727, 0.572934  ,
        0.66208651, 0.57413793, 0.54540197, 0.55324959, 0.55543767,
        0.55567172, 0.56010782, 0.54611399, 0.58835759],
       [0.15049299, 0.09675583, 0.09955996, 0.13489896, 0.60498221,
        0.98894472, 0.23317684, 0.0994186 , 0.13352273, 0.1031614 ,
        0.38625954, 0.1316092 , 0.09600925, 0.10322228, 0.09655172,
        0.111

In [9]:
data=pd.concat((happy,sad))

In [10]:
data.shape

(200, 20)

In [11]:
X=data.iloc[:,:19].values
Y=data.iloc[:,19:].values

In [12]:
X=scaler.fit_transform(X)

In [13]:
X

array([[0.53502854, 0.54866249, 0.54620462, 0.55488804, 0.55338078,
        0.55879397, 0.65686275, 0.58546512, 0.61988636, 0.58735441,
        0.65089059, 0.59425287, 0.52689416, 0.54396505, 0.54588859,
        0.52639833, 0.53315364, 0.53523316, 0.54158004],
       [0.51686559, 0.50256118, 0.4840484 , 0.49754233, 0.50978648,
        0.45728643, 0.60577915, 0.50465116, 0.54431818, 0.51358846,
        0.61628499, 0.51321839, 0.5708502 , 0.459858  , 0.45623342,
        0.47516989, 0.48787062, 0.46632124, 0.51611227],
       [0.55526725, 0.59874787, 0.57480748, 0.59803386, 0.58185053,
        0.51557789, 0.65325077, 0.59186047, 0.62272727, 0.5995563 ,
        0.69262087, 0.58505747, 0.61364951, 0.57728017, 0.56657825,
        0.5781495 , 0.59568733, 0.58082902, 0.60446985],
       [0.51894136, 0.57427433, 0.55830583, 0.58110322, 0.53914591,
        0.50954774, 0.63570691, 0.59069767, 0.60397727, 0.58957293,
        0.6264631 , 0.56781609, 0.56969346, 0.51501912, 0.52785146,
        0.534

In [14]:
from sklearn.naive_bayes import GaussianNB

model=GaussianNB()

model.fit(X,Y)

c:\Users\Rohit Maity\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [18]:
model.classes_

array([0, 1], dtype=int64)

In [16]:
Y_Pred=model.predict(X)

In [20]:
from sklearn.metrics import accuracy_score,confusion_matrix

accuracy_score(Y,Y_Pred)

0.55

In [21]:
confusion_matrix(Y,Y_Pred)

array([[90, 10],
       [80, 20]], dtype=int64)